#!/bin/bash
#
#                         License
#
# Copyright (C) 2021  David Valin dvalin@redhat.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# This script automates the execution of stress-ng.  It will determine the
# set of default run parameters based on the system configuration.
#

commit="none"
stress_ng_wrapper_version="v1.00"
test_name="stress_ng"
results_file="results_${test_name}.csv"
arguments="$@"
script_dir=$(realpath $(dirname $0))

exit_out()
{
	echo $1
	exit $2
}

if [ ! -f "/tmp/${test_name}.out" ]; then
	command="${0} $@"
	echo $command
	$command &> /tmp/${test_name}.out
	rtc=$?
	cat /tmp/${test_name}.out
	rm /tmp/${test_name}.out
	exit $rtc 
fi

curdir=$(dirname $(realpath $0))
if [[ $0 == "./"* ]]; then
	chars=`echo $0 | awk -v RS='/' 'END{print NR-1}'`
	if [[ $chars == 1 ]]; then
		run_dir=`pwd`
	else
		run_dir=`echo $0 | cut -d'/' -f 1-${chars} | cut -d'.' -f2-`
		run_dir="${curdir}${run_dir}"
	fi
elif [[ $0 != "/"* ]]; then
	dir=`echo $0 | rev | cut -d'/' -f2- | rev`
	run_dir="${curdir}/${dir}"
else
	chars=`echo $0 | awk -v RS='/' 'END{print NR-1}'`
	run_dir=`echo $0 | cut -d'/' -f 1-${chars}`
	if [[ $run_dir != "/"* ]]; then
		run_dir=${curdir}/${run_dir}
	fi
fi
cd $run_dir

setup_done=0
out_file=""
show_usage=0
opts_file="${run_dir}/test_opts"

TOOLS_BIN="$HOME/test_tools"
export TOOLS_BIN

usage()
{
	echo "Usage $1:"
	echo "  --opts_file <path>:  Test option file to use, default is test_opts"
	source $TOOLS_BIN/general_setup --usage
	exit $E_USAGE
}

attempt_tools_wget()
{
	if [[ ! -d "$TOOLS_BIN" ]]; then
		wget ${tools_git}/archive/refs/heads/main.zip
		if [[ $? -eq 0 ]]; then
			unzip -q main.zip
			mv test_tools-wrappers-main ${TOOLS_BIN}
			rm main.zip
		fi
	fi
}

attempt_tools_curl()
{
	if [[ ! -d "$TOOLS_BIN" ]]; then
		curl -L -O ${tools_git}/archive/refs/heads/main.zip
		if [[ $? -eq 0 ]]; then
			unzip -q main.zip
			mv test_tools-wrappers-main ${TOOLS_BIN}
			rm main.zip
		fi
	fi
}

attempt_tools_git()
{
	if [[ ! -d "$TOOLS_BIN" ]]; then
		git clone $tools_git "$TOOLS_BIN"
		if [ $? -ne 0 ]; then
			exit_out "Error: pulling git $tools_git failed." 101
		fi
	fi
}

install_test_tools()
{
	#
	# Clone the repo that contains the common code and tools
	#
	tools_git=https://github.com/redhat-performance/test_tools-wrappers
	found=0
	for arg in "$@"; do
		if [ $found -eq 1 ]; then
			tools_git=$arg
			found=0
		fi
		if [[ $arg == "--tools_git" ]]; then
			found=1
		fi

		#
		# We do the usage check here, as we do not want to be calling
		# the common parsers then checking for usage here.  Doing so will
		# result in the script exiting with out giving the test options.
		#
		if [[ $arg == "--usage" ]]; then
			show_usage=1
		fi
	done

	#
	# Check to see if the test tools directory exists.  If it does, we do not need to
	# clone the repo.
	#
	attempt_tools_wget
	attempt_tools_curl
	attempt_tools_git

	if [ $show_usage -eq 1 ]; then
		usage $1
	fi
}

execute_stress_ng()
{
	while IFS= read -r test_info
	do
		echo executing $test_info
		test_run=$(echo $test_info | cut -d, -f1)
		test_opts=$(echo $test_info | cut -d, -f2)
		for iter in $(seq 1 1 $to_times_to_run); do
			if [[ $to_use_pcp -eq 1 ]]; then
				start_pcp_subset
				results2pcp_add_value "iteration:${iter}"
				results2pcp_add_value_commit
			fi
			start_time=$(retrieve_time_stamp)
			echo stress-ng --metrics-brief $test_opts
			stress-ng --metrics-brief $test_opts > ${run_dir}/results_${test_run}_iteration_${iter}.data
			end_time=$(retrieve_time_stamp)
			echo Start_time: $start_time >>  ${run_dir}/results_${test_run}_iteration_${iter}.data
			echo End_time: $end_time >>  ${run_dir}/results_${test_run}_iteration_${iter}.data
			if [[ $to_use_pcp -eq 1 ]]; then
				val=$(grep metrc ${run_dir}/results_${test_run}_iteration_${iter}.data | tail -1 | awk '{print $9}')
				test_run=$(echo $test_run | sed "s/-/_/g")
				results2pcp_add_value "${test_run}:${val}"
				results2pcp_add_value_commit
				stop_pcp_subset
				reset_pcp_om
			fi
		done
	done < "$opts_file"
}

generate_csv_file()
{
	record=1
	rm -f worker
	$TOOLS_BIN/test_header_info --front_matter --results_file worker --host $to_configuration --sys_type $to_sys_type --tuned $to_tuned_setting --results_version $stress_ng_wrapper_version --test_name $test_name --field_header "test,bogo_ops_per_sec"

	ls results*data | cut -d'_' -f2- | rev | cut -d'_' -f3- | rev |sort -u > test_ran

	while IFS= read -r test_exec
	do
		start_time=""
		separ=""
		add_up=""
		record=1
		for res in $(ls results_${test_exec}* ); do
			grep -q "not implemented on this system" $res
			if [[ $? -eq 0 ]]; then
				record=0
			fi
			if [[ $start_time == "" ]]; then
				start_time=$(grep Start_time: $res | cut -d' ' -f2)
			fi
			end_time=$(grep End_time: $res | cut -d' ' -f2)
			val=$(grep metrc $res | tail -1 | awk '{print $9}')
			add_up=${add_up}${separ}${val}
			separ="+"
		done
		if [[ $record -eq 1 ]]; then
			value=$(echo "scaler=2;($add_up)/${to_times_to_run}" | bc)
			test_out=$(echo $test_exec | sed "s/-/_/g")
			echo $test_out,$value,$start_time,$end_time >> worker
		else
			echo "# $test_exec not implemented on this system" >> $results_file
		fi
	done < "test_ran"
	cat worker >> $results_file
	rm worker test_ran
}

install_test_tools "$@"

#
# Variables set by general setup.
#
# TOOLS_BIN: points to the tool directory
# to_home_root: home directory
# to_configuration: configuration information
# to_times_to_run: number of times to run the test
# to_run_label: Label for the run
# to_user: User on the test system running the test
# to_sys_type: for results info, basically aws, azure or local
# to_sysname: name of the system
# to_tuned_setting: tuned setting
#

pushd $curdir 2> /dev/null
source "$TOOLS_BIN/general_setup" "$@"
popd 2> /dev/null
# Gather hardware information
$TOOLS_BIN/gather_data ${curdir}

ARGUMENT_LIST=(
	"opts_file"
)

NO_ARGUMENTS=(
	"usage"
)

# read arguments
opts=$(getopt \
	--longoptions "$(printf "%s:," "${ARGUMENT_LIST[@]}")" \
	--longoptions "$(printf "%s," "${NO_ARGUMENTS[@]}")" \
	--name "$(basename "$0")" \
	--options "h" \
	-- "$@"
)

eval set -- $opts

while [[ $# -gt 0 ]]; do
	case "$1" in
		--opts_file)
			opts_file=${2}
			shift 2
		;;
		--usage)
			usage $0
		;;
		-h)
			usage $0
		;;
		--)
			break
		;;
		*)
			echo option not found $1
			usage $0
		;;
	esac
done

if [ -d /${to_home_root}/${to_user} ]; then
	cd /${to_home_root}/${to_user}
fi

package_tool --no_packages $to_no_pkg_install --wrapper_config $curdir/../stress_ng.json

# Get PCP setup if we're using it
if [[ $to_use_pcp -eq 1 ]]; then
	source $TOOLS_BIN/pcp/pcp_commands.inc
	setup_pcp
	pcp_cfg=$TOOLS_BIN/pcp/default.cfg
	pcpdir=/tmp/pcp_`date "+%Y.%m.%d-%H.%M.%S"`
        echo "Start PCP"
        echo start_pcp ${pcpdir}/ ${test_name} $pcp_cfg
        start_pcp ${pcpdir}/ ${test_name} $pcp_cfg
fi

pushd ${run_dir} > /dev/null
rm -f results*data *.csv
execute_stress_ng
generate_csv_file

# Shutdown PCP and clean up after ourselves
if [[ $to_use_pcp -eq 1 ]]; then
	shutdown_pcp
fi

${TOOLS_BIN}/save_results --curdir $curdir --home_root $to_home_root --other_files "*_summary,run*log,test_results_report,${pcpdir}" --results $results_file --test_name stress_ng --tuned_setting=$to_tuned_setting --version $stress_ng_wrapper_version --user $to_user 
$TOOLS_BIN/csv_to_json $to_json_flags --csv_file ${results_file} --output_file results_stress_ng.json
if [[ $? -ne 0 ]]; then
	exit_out "Failed: $TOOLS_BIN/csv_to_json $to_json_flags --csv_file ${results_file} --output_file results_stress_ng.json" $E_GENERAL

fi
$TOOLS_BIN/verify_results $to_verify_flags --schema_file $script_dir/../result_schema.py --class_name Stress_ng_Results --file results_stress_ng.json
if [[ $? -ne 0 ]]; then
	exit_out "CSV contains invalid data." $E_VALIDATION_FAIL
fi
popd > /dev/null
exit $E_SUCCESS
